In [3]:
import numpy as np

a=[1,2,3,4,5]
b=np.array(a)
b

array([1, 2, 3, 4, 5])

In [4]:
dic = {'a':1, 'b':2, 'c':3}
a = np.array([list(dic.keys()), list(dic.values())])


In [5]:
a

array([['a', 'b', 'c'],
       ['1', '2', '3']], dtype='<U11')

In [6]:
a=[[11, 12, 13, 14],

 [15, 16, 17, 18],

 [19, 20, 21, 22]]

b=np.array(a)

In [7]:
b[1:3,1:3]

array([[16, 17],
       [20, 21]])

In [8]:
b[1:,1:3]

array([[16, 17],
       [20, 21]])

In [11]:
b[-2:,-3:-1]

array([[16, 17],
       [20, 21]])

In [12]:
b[1:,1:]

array([[16, 17, 18],
       [20, 21, 22]])

In [3]:
import datetime
n = datetime.datetime.now()
n.isocalendar()
# (2017, 45, 1)
n = datetime.datetime(2017, 11, 6)
n.isocalendar()
n.isocalendar()[1]
# (2017, 44, 7)

45

In [7]:
age = {"a":[19,20,23,46,21,25,26,25,28,31,37,24,28,34,38,33,32,29,27,24]}

In [8]:
import pandas as pd
import numpy as np

In [9]:
b=pd.DataFrame(age)

In [10]:
b.describe()

a
count  20.0000
mean   28.5000
std     6.7317
min    19.0000
25%    24.0000
50%    27.5000
75%    32.2500
max    46.0000

In [11]:
%config Completer.use_jedi = False

In [1]:
import pandas as pd 
import seaborn as sns
df =pd.read_csv('problem1.csv')

In [2]:
df['date'] =df['year'].astype('str')+'-'+df['month'].astype('str')+'-'+df['day'].astype('str')

In [3]:
df['date'] = pd.to_datetime(df['date'])

In [4]:
df['date'].dt.strftime('%Y-%m-%d')

0      2016-01-01
1      2016-01-02
2      2016-01-03
3      2016-01-04
4      2016-01-05
          ...    
343    2016-12-27
344    2016-12-28
345    2016-12-29
346    2016-12-30
347    2016-12-31
Name: date, Length: 348, dtype: object

In [5]:
df['date']

0     2016-01-01
1     2016-01-02
2     2016-01-03
3     2016-01-04
4     2016-01-05
         ...    
343   2016-12-27
344   2016-12-28
345   2016-12-29
346   2016-12-30
347   2016-12-31
Name: date, Length: 348, dtype: datetime64[ns]

In [33]:
v = pd.DataFrame(pd.date_range(start=df['date'].dt.strftime('%Y-%m-%d').min(), end=df['date'].dt.strftime('%Y-%m-%d').max()))[0].dt.strftime('%Y-%m-%d').values
v

array(['2016-01-01', '2016-01-02', '2016-01-03', '2016-01-04',
       '2016-01-05', '2016-01-06', '2016-01-07', '2016-01-08',
       '2016-01-09', '2016-01-10', '2016-01-11', '2016-01-12',
       '2016-01-13', '2016-01-14', '2016-01-15', '2016-01-16',
       '2016-01-17', '2016-01-18', '2016-01-19', '2016-01-20',
       '2016-01-21', '2016-01-22', '2016-01-23', '2016-01-24',
       '2016-01-25', '2016-01-26', '2016-01-27', '2016-01-28',
       '2016-01-29', '2016-01-30', '2016-01-31', '2016-02-01',
       '2016-02-02', '2016-02-03', '2016-02-04', '2016-02-05',
       '2016-02-06', '2016-02-07', '2016-02-08', '2016-02-09',
       '2016-02-10', '2016-02-11', '2016-02-12', '2016-02-13',
       '2016-02-14', '2016-02-15', '2016-02-16', '2016-02-17',
       '2016-02-18', '2016-02-19', '2016-02-20', '2016-02-21',
       '2016-02-22', '2016-02-23', '2016-02-24', '2016-02-25',
       '2016-02-26', '2016-02-27', '2016-02-28', '2016-02-29',
       '2016-03-01', '2016-03-02', '2016-03-03', '2016-

In [32]:
v1 = pd.DataFrame(pd.date_range(df['date'].min(), df['date'].max()))
v1

0
0   2016-01-01
1   2016-01-02
2   2016-01-03
3   2016-01-04
4   2016-01-05
..         ...
361 2016-12-27
362 2016-12-28
363 2016-12-29
364 2016-12-30
365 2016-12-31

[366 rows x 1 columns]

In [38]:
print(type(v1[0]))

<class 'pandas.core.series.Series'>


In [39]:
print(type(v))

<class 'numpy.ndarray'>


In [28]:
a=set(v) - set(df['date'].dt.strftime('%Y-%m-%d'))
a1=set(v1) - set(df['date'])

In [29]:
a

{'2016-02-13',
 '2016-02-14',
 '2016-02-29',
 '2016-08-17',
 '2016-08-18',
 '2016-08-19',
 '2016-08-20',
 '2016-08-21',
 '2016-08-22',
 '2016-08-24',
 '2016-08-25',
 '2016-08-26',
 '2016-08-27',
 '2016-08-29',
 '2016-08-31',
 '2016-09-01',
 '2016-09-02',
 '2016-10-30'}

In [30]:
a1

{Timestamp('2016-02-13 00:00:00'),
 Timestamp('2016-02-14 00:00:00'),
 Timestamp('2016-02-29 00:00:00'),
 Timestamp('2016-08-17 00:00:00'),
 Timestamp('2016-08-18 00:00:00'),
 Timestamp('2016-08-19 00:00:00'),
 Timestamp('2016-08-20 00:00:00'),
 Timestamp('2016-08-21 00:00:00'),
 Timestamp('2016-08-22 00:00:00'),
 Timestamp('2016-08-24 00:00:00'),
 Timestamp('2016-08-25 00:00:00'),
 Timestamp('2016-08-26 00:00:00'),
 Timestamp('2016-08-27 00:00:00'),
 Timestamp('2016-08-29 00:00:00'),
 Timestamp('2016-08-31 00:00:00'),
 Timestamp('2016-09-01 00:00:00'),
 Timestamp('2016-09-02 00:00:00'),
 Timestamp('2016-10-30 00:00:00')}

In [31]:
len(a1)

18

In [26]:
df['date']

0     2016-01-01
1     2016-01-02
2     2016-01-03
3     2016-01-04
4     2016-01-05
         ...    
343   2016-12-27
344   2016-12-28
345   2016-12-29
346   2016-12-30
347   2016-12-31
Name: date, Length: 348, dtype: datetime64[ns]

In [11]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns
import scipy.stats as spst

In [12]:
a = pd.read_csv('https://raw.githubusercontent.com/DA4BAM/dataset/master/boston.csv')

In [13]:
a.head()

crim    zn  indus  chas    nox     rm   age     dis  rad  tax  ptratio  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296     15.3   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242     17.8   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242     17.8   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222     18.7   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222     18.7   

   lstat  medv  
0   4.98  24.0  
1   9.14  21.6  
2   4.03  34.7  
3   2.94  33.4  
4   5.33  36.2

In [16]:
spst.pearsonr(round(a['tax'],4), a['medv'])

PearsonRResult(statistic=-0.4685359335677671, pvalue=5.637733627689083e-29)

In [17]:
a["tax1"]=round(a["tax"],4)

In [18]:
spst.pearsonr(a['tax1'], a['medv'])

PearsonRResult(statistic=-0.4685359335677671, pvalue=5.637733627689083e-29)

In [19]:
spst.pearsonr(a['tax'], a['medv'])

PearsonRResult(statistic=-0.4685359335677671, pvalue=5.637733627689083e-29)